# Here the instructions define the application as services.
# This service is built from the Dockerfile in the current directory.
services:
  backend:
    build:
      context: ./
    command: npm run start
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    networks:
      - private
    secrets:
      - db-password
  db:
    image: mariadb:10.6.4-focal # mariadb is mysql but faster and smaller.
    container_name: user_data_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    # environment:
    #   - MYSQL_DATABASE=example
    #   - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    # command: '--default-authentication-plugin=mysql_native_password'
    # restart: always
    secrets:
      - db-password
networks:
  private:
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt