# Here the instructions define the application as services.
# This service is built from the Dockerfile in the current directory.
services:
  backend:
    build:
      args:
      - NODE_ENV=production
      context: ./
    command: npm run start
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=production
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
    networks:
      - private
      # - public
    secrets:
      - db-password
    # volumes:
    #   - ./backend/src:/code/src:ro
    #   - ./backend/package.json:/code/package.json
    #   - ./backend/package-lock.json:/code/package-lock.json
    #   - back-notused:/opt/app/node_modules
  db:
    image: mariadb:10.6.4-focal # mariadb is mysql but faster and smaller.
    container_name: user_data_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    # environment:
    #   - MYSQL_DATABASE=example
    #   - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    # command: '--default-authentication-plugin=mysql_native_password'
    # restart: always
    secrets:
      - db-password
networks:
  # public:
  private:
volumes:
  # back-notused:
  db-data:
secrets:
  db-password:
    file: db/password.txt